### ISSUE TITLE
Design Women & Web Lit site

### ISSUE THREAD

**Issue by flukeout** [mozilla/womenandweb#11]
Moving on from #4 - let's get into some visual design. I made two options based on the wireframes.
- **Option 1** - https://redpen.io/wt2d220d6e4acb9655
- **Option 2** - https://redpen.io/mw37f8040fc3d8f4a2

Please leave your thoughts and feedback, looking for big-picture stuff like
- Overall feel & tone
- Color palette
- Choice of imagery for the header
- etc.

Will ping the design team for a review as well.

cc @amirad 

We've also gathered feedback on the Wireframes during our crit, which raised some good questions. I haven't acted on them yet so as not to delay the visual design phase, but it would be good to address them so we can make changes now or soon...
- Should we include content & calls to action for people looking to find an existing club?
  - We only really target the organizers with our current CTA
- Should we include a case study or a more personal story of some sort? 
  - We could expand on the quote that is currently in there maybe, add a face and name?

**Comment by amirad** [comment]
Thanks @flukeout - these are looking great! 

I have pretty strong feels towards option 1 right now. It feels more professional and clean to me. It also doesn't lead with pink colours, which tbh is a huge turnoff for me. 

As for the other feedback, 

--> I don't think we are able to properly search for specific clubs, especially those related to women. Maybe that's a tag and build into the event reporter???? In the case studies section there are a tonnnnn of other examples of women clubs if there is a way to pull those out. 

--> I sadly don't have a name or picture for the quote (anonymous survey) but am open to a general picture from Nairobi being placed there as a filler if that works. Like this one: https://www.flickr.com/photos/amirad/27051356961/in/album-72157666127395174/ or https://www.flickr.com/photos/amirad/26515914023/in/album-72157666127395174/

**Comment by flukeout** [comment]
Posted an updated design based on the feedback so far
- **Option 1b** - https://redpen.io/nb937da61b876d5cf1

cc @amirad 

Once we feel closer to a final version, I'll work on a Mobile layout.

**Comment by amirad** [comment]
Looking soooo great @flukeout - added some final tweeks, mostly wording. Did a couple verbal checks with @jvallera and @kaythaney and we all feel good.

I can update the blogpost wording and stuff on my own after in markup right? I don't need to worry about doing that now? Same for logos?

**Comment by flukeout** [comment]
Correct, although for the Collaborator logos, we should get the initial list and logos for launch.

I got some feedback that the blue box in the _What We Do_ section makes that content feel secondary to the copy beside it, so I created another version for contrast, please take a look...
- https://redpen.io/pg566c3520217fb839

@amirad, let me know your thoughts on this option - deciding on this won't affect implementation so no worries.

**Next up - Mobile Design**
As a start, I think we can just turn this design into a single-column layout and include all of the content. This will make the page suuuuuuper long though, so we might want to think about...
- Only including some of the content on mobile
  - I think we can cut...
    - The resources links (the resources proooobably aren't mobile optimized anyway?)
    - The photos (or just leave one)
    - The testimonial
- Shortening certain bits of content
  - We can limit the Blog Post sections to just the title
- Adding in some kind of navigation for the mobile experience

**Comment by amirad** [comment]
Cool. Gathering logos now. 

Feedback in redpen

**Comment by flukeout** [comment]
Closing and moving to implementation issue - #13
