### ISSUE TITLE
Set up scaffolding

### ISSUE THREAD

**Issue by gvn** [mozilla/womenandweb#3]
- [x] A single web page will be generated from markdown partials.
- [x] We will leverage [mofo-bootstrap](https://github.com/mozilla/mofo-bootstrap) for styling.
- [x] Editing of markdown will take place on `master` branch. Travis will monitor `master` for changes, run the build task, and deploy to gh-pages automagically. #6 
- [x] For development purposes, there will be a live-reload task monitoring the markdown and CSS for changes, which will rebuild and reload the local page in browser.

**Comment by gvn** [comment]
CC: @gideonthomas @flukeout

**Comment by flukeout** [comment]
Looks good, do you have a sense of what the syntax for including the partials in the HTML will be?

**Comment by gvn** [comment]
I'm working on that right now! Should be very simple...

**Comment by gideonthomas** [comment]
This looks great, very organized! @gvn, would you be able to file separate issues based on this

**Comment by gvn** [comment]
Yep, I have a PR that addresses 3 of the tasks, but I'll make another for the deployment stuff.
