### ISSUE TITLE
Quote missing in mobile view

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/womenandweb#40]
The opening quotation mark is almost fully out of view in mobile view. Side-note, can we change the quotes to be less typewriter-y and more like what the design shows?

**Comment by flukeout** [comment]
Changed the quotes so they only appear outside of the quote in wide viewports but collapse into the quote itself on narrow views.

Will find something type-writery later, can't find any good system fonts and don't want to include an external font just for the quotes right now. Good eye though!!
