### ISSUE TITLE
Blog posts look like one giant post in mobile view

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/womenandweb#41]
The blog posts fall one below the other in mobile view but they are joined without any demarcation like so:
<img width="319" alt="screen shot 2016-08-29 at 10 21 20 pm" src="https://cloud.githubusercontent.com/assets/5816130/18073907/f736430c-6e36-11e6-8e30-18e07ce7b415.png">

**Comment by flukeout** [comment]
Fix'd
