### ISSUE TITLE
Quotation mark out of place

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/womenandweb#44]
![screen shot 2016-08-30 at 5 06 29 pm](https://cloud.githubusercontent.com/assets/5816130/18107023/2a2b2136-6ed4-11e6-8f59-522ba39e35ec.png)

It looks like the close quotation mark is way down. Don't know if this is a real issue though

**Comment by flukeout** [comment]
It's fine! Even @natalieworth said so.
