### ISSUE TITLE
Add Sticker Mule to sponsors list.

### ISSUE THREAD

**Issue by flukeout** [mozilla/womenandweb#50]
Hey @amirad, moving this issue to here instead of email.

Right now, I've got this design running locally...

**Desktop**
![image](https://cloud.githubusercontent.com/assets/25212/21461492/ce466758-c906-11e6-9235-6227c6535d84.png)

**Mobile**
![image](https://cloud.githubusercontent.com/assets/25212/21461501/d9e407b4-c906-11e6-8326-8f80f0d6d55c.png)

The logo links to https://www.stickermule.com/

Let me know if you'd like any changes and I'll push it live.

**Comment by amirad** [comment]
That works! Thanks Luke. Feel free to push.

**Comment by flukeout** [comment]
Will push today, cheers.

**Comment by amirad** [comment]
You da best. Thanks!

**Comment by flukeout** [comment]
Cool - PR is in, and will land as soon as @gvn gives it a once-over.
