### ISSUE TITLE
Add Privacy link to footer

### ISSUE THREAD

**Issue by hannahkane** [mozilla/womenandweb#53]
Text: Privacy
Target:  https://www.mozilla.org/privacy/websites/
Position: After Legal, on the far right

**Comment by mmmavis** [comment]
@gvn can I update `mofo-bootstrap` dependency to the latest version and pull footer styling from there?

**Comment by mmmavis** [comment]
Um I think I'll add the privacy link in first and file a separate PR for updating mofo-bootstrap verison.
