### ISSUE TITLE
Set up Deployment

### ISSUE THREAD

**Issue by gvn** [mozilla/womenandweb#6]
When commits are made to `master` it should trigger a deploy task to `gh-pages`.

**Comment by gvn** [comment]
@gideonthomas @hannahkane 

Are we ok with not having a staging server at this point?

With this deployment scheme any updates to `master` will go live immediately.

**Comment by gideonthomas** [comment]
I think that works for me! Maybe we can add some kind of markdown validation using CI?

**Comment by gvn** [comment]
Yeah, I think that's a good idea. I'll look into that...
