### ISSUE TITLE
Deployments don't seem to be running

### ISSUE THREAD

**Issue by gvn** [mozilla/womenandweb#61]
It seems that the automated deployments triggered from commits to `master` aren't happening.

The last deploy to `gh-pages` was March 31, but there have been commits since then.

This may have something to do with the failure of [this commit](https://github.com/mozilla/womenandweb/commit/7cfdcdbe9956899e0b5f06eebdc873eab527922b).

**Comment by gvn** [comment]
@gideonthomas can you look into this?

**Comment by gideonthomas** [comment]
@gvn looks like you fixed this?

**Comment by gideonthomas** [comment]
oh nvm, looks like it's still at March 31st

**Comment by gideonthomas** [comment]
Fixed
